### ISSUE TITLE
Saving indicator on spell edit page

### ISSUE THREAD

**Issue by Runi-c** [srfoster/codespells-spell-sharing-front-end#56]
I can't easily tell right now when the frontend has sent the request to the backend to save the spell as I'm typing.

My suggestion: Store the promise for the spell update request. Display a little spinner somewhere on the page (top right of the code mirror?) when the promise is pending. It changes to a checkmark when the promise resolves. If it rejects, a modal or alert showing the error should appear.

**Comment by justin-foster-91** [comment]
Saving indicator had been present but only flickered briefly. It now remains for a second on the top right of the spell details page each time a save is occurring. 

Leaving the issue open for the moment pending feedback.

**Comment by Runi-c** [comment]
The saving indicator only appears once the API request has actually been sent, but it should appear as soon as [this debounce](https://github.com/srfoster/codespells-spell-sharing-front-end/blob/master/src/Components/Dashboard/SpellDetails.js#L316) starts ticking.

Also, I still think we could use a persistent check-mark after saving completes so that I can always just glance over and confirm that the spell in the database is the one on my screen.
